### ISSUE TITLE
DQ Issue unable to identify Id needs to be removed in dq_report & Fix_dq remove them

### ISSUE THREAD

**Issue by GDGauravDutta** [AutoViML/pandas_dq#1]
![image](https://user-images.githubusercontent.com/62606251/230534247-a92baa15-3b79-44af-88c8-dc1bae7b508e.png)

**Comment by GDGauravDutta** [comment]
![image](https://user-images.githubusercontent.com/62606251/230534770-8027f1e6-b3c6-446a-b770-234e497985f5.png)
   Algorithm needs to remove id like feaatures

**Comment by AutoViML** [comment]
Hi @GDGauravDutta 👍 
Thanks for trying out pandas_dq. I have fixed this already. Can you please upgrade this way and then check?
```
pip install pandas_dq --ignore-installed --no-cache-dir
```

If you see version 1.7 or higher, then you have the right version.
Thanks
Auto Vimal team

**Comment by AutoViML** [comment]
It now removes ID like features,    On Thursday, April 6, 2023 at 11:25:19 PM EDT, GDGauravDutta ***@***.***> wrote:  
 
 



Algorithm needs to remove id like feaatures
