### ISSUE TITLE
Compared to FeatureWiz?

### ISSUE THREAD

**Issue by sideshot** [AutoViML/pandas_dq#5]
Cool script.  Is this supposed to be an alternative to FeatureWiz?

**Comment by AutoViML** [comment]
No. You need to use pandas-dq first to fix data quality issues in your data and then apply featurewiz to create new features and/or do feature selection.
Does that make sense?

    On Wednesday, February 7, 2024 at 06:15:07 PM EST, Richard ***@***.***> wrote:  
 
 


Cool script. Is this supposed to be an alternative to FeatureWiz?
